### ISSUE TITLE
Crossfiledialog does not work under WSL

### ISSUE THREAD

**Issue by VogelFlug** [maikelwever/crossfiledialog#7]
In line 27 of wrapper.py, an error is thrown, because the code assumes it is being run under Linux.

**Comment by maikelwever** [comment]
Please run the following commands in a WSL Bash shell and provide the results here:

```bash
echo $DESKTOP_SESSION
echo $XDG_CURRENT_DESKTOP
which kdialog
which zenity
```

**Comment by NebularNerd** [comment]
If this helps on my setup with WSL Ubuntu for `which zenity` I get `/usr/bin/zenity`. Nothing else comes back for the rest, I have GTK installed for run GUI apps, if you don't have that I don't think there is a file dialog available by default.

**Comment by maikelwever** [comment]
> If this helps on my setup with WSL Ubuntu for `which zenity` I get `/usr/bin/zenity`. Nothing else comes back for the rest, I have GTK installed for run GUI apps, if you don't have that I don't think there is a file dialog available by default.

Does `crossfiledialog` work as-is for you, or do you encounter the same issue as OP? If it works, this is just a documentation/error handling issue.

**Comment by NebularNerd** [comment]
Just tried with a very minimal example
```
import crossfiledialog
foldername = crossfiledialog.choose_folder()
print (foldername)
```

When run no dialog appears, if I `Ctrl-C` I get
```
^CTraceback (most recent call last):
  File "/home/nebularnerd/Downloads/test_crosfile.py", line 3, in <module>
    foldername = crossfiledialog.choose_folder()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nebularnerd/.local/lib/python3.12/site-packages/crossfiledialog/zenity.py", line 222, in choose_folder
    result = run_zenity('file-selection', 'directory', **zenity_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nebularnerd/.local/lib/python3.12/site-packages/crossfiledialog/zenity.py", line 43, in run_zenity
    stdout, stderr = process.communicate()
                     ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 1209, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 2115, in _communicate
    ready = selector.select(timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
```

So it seems to be able to see zenity but not draw a dialog box.
